name: test autoinstall with brew

on:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:
    types:
      - test

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # TODO add windows?
        neovim-version: [stable] #, nightly] # TODO run fortnightly on nightly
        plugin-manager: [lazy] #, neovim]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}

      # prepare to use actions from this repo
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
      - run: npm ci

      - name: Run neoclip
        id: install-neoclip
        uses: ./actions/run-neoclip
        with:
          plugin-manager: ${{ matrix.plugin-manager }}

      - name: Check health
        uses: ./actions/check-report
        with:
          nvim: ${{ steps.install-neoclip.outputs.nvim }}
